from pages.home_page import HomePage

def test_correct_login(driver):
    home_page = HomePage(driver)
    home_page.go_to()
    home_page.login("standard_user", "secret_sauce")
    home_page.login_button()
    home_page.products_verif()
    home_page.add_to_cart()
    home_page.add_to_cart2()
    home_page.click_on_cart()
    home_page.your_cart_verif()
    home_page.products_in_the_cart_verif()
    home_page.checkout_()
    home_page.your_info_verif()
    home_page.fill_checkout_fields("Amina", "Suljic" , "71000")
    home_page.checkout_overview_verif()
    home_page.product1_verif()
    home_page.product2_verif() 
    home_page.finish()
    home_page.checkout_complete()
    home_page.click_on_menu()
    home_page.logout()
    home_page.login_verif()
